spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/easybuy?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      maxWait: -1
      initialSize: 10
      minIdle: 100
      maxActive: 200
      testOnBorrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.71.131
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

mybatis:
  typeAliasesPackage: com.lhl.domain
  mapperLocations: classpath:com/lhl/dao/*.xml
  # 开启驼峰
  configuration:
    map-underscore-to-camel-case: true

redis:
  host: 192.168.71.131
  port: 6379
  timeout: 10
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 3

pageCache:
  enbale: true